apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: baka-chief-nginx-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Mi
  hostPath:
    path: /baka-media/web/baka-chief/nginx/
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
